version: "3.8"

services:
  terraform:
    container_name: terraform
    build: ./terraform
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - ENV=LOCAL
      - aws=/usr/local/aws-cli/v2/current/bin/aws
    
    volumes:
      - ./terraform:/terraform